# Gemini Robot 설정 파일 (데모 모드 - API 없이)

/**:
  ros__parameters:
    # 에이전트 설정
    timer_period_sec: 0.8        # 에이전트 루프 주기 (초)
    max_steps: 300               # 최대 스텝 수
    max_runtime_sec: 600         # 최대 실행 시간 (초)
    
    # 안전 설정
    safety_stop_distance_m: 0.5  # 안전 정지 거리 (미터)
    max_linear_speed: 0.5        # 최대 선속도 (m/s)
    max_angular_speed: 1.0       # 최대 각속도 (rad/s)
    
    # 비전 설정
    publish_rate_hz: 2.0         # 비전 발행 주기 (Hz)
    
    # Gemini API 설정 (비활성화)
    use_gemini_api: false        # API 사용 안 함 - 규칙 기반 플래너 사용
    gemini_model_id: "gemini-robotics-er-1.5-preview"
    gemini_temperature: 0.5
    gemini_thinking_budget: 0.2

